# Generated by Django 5.0.6 on 2024-06-07 08:22

from django.db import migrations
from django.contrib.postgres.operations import CITextExtension

class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        CITextExtension()    
    ]
